# # Unique project key
# sonar.projectKey=dar_elsoker

# # Project name
# sonar.projectName=DarElsoker

# # Project version
# sonar.projectVersion=1.0

# # Path to source directories (comma-separated)
# sonar.sources=.

# # Optional: path to test source directories
# # sonar.tests=test

# # Optional: path to exclude specific files or directories
# # sonar.exclusions=**/excluded_dir/**,**/excluded_file.js

# # Optional: language setting (if your project is in a specific language like JavaScript)
# # sonar.language=js

# # Encoding of the source code
# sonar.sourceEncoding=UTF-8
sonar.projectKey=MegaDevelopment_dar-elsokar-frontend_AZEe70uPf5fhilN0BtC-
