# Configure here general information about the environment, such as SonarQube server connection details for example

# No trailing slash!
sonar.host.url=http://localhost:9000

# Use your SonarQube token for authentication
sonar.login=sqp_c7a997c079b521be63b51b5c230136c93cba0f1a
